"""The commit-msg hook rejects `Co-Authored-By: Claude` trailers (POLICY.md P5.5).

The trailer is injected by default by some commit tooling, so a written reminder
does not hold -- it was violated twice in one day (2026-08-28). This hook is the
mechanical block. The tests here are what make it a guard rather than a decoration
(P6.2): each drives the hook against a real message file and asserts on the exit
code, so a hook that could never reject would fail `test_it_rejects_the_trailer`.
"""
from __future__ import annotations

import stat
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
HOOK = REPO_ROOT / ".githooks" / "commit-msg"


def _run_hook(tmp_path: Path, message: str) -> int:
    msg_file = tmp_path / "COMMIT_EDITMSG"
    msg_file.write_text(message, encoding="utf-8")
    result = subprocess.run(
        [str(HOOK), str(msg_file)], capture_output=True, text=True, check=False
    )
    return result.returncode


def test_the_hook_exists_and_is_executable():
    assert HOOK.is_file(), "the commit-msg hook is missing"
    mode = HOOK.stat().st_mode
    assert mode & stat.S_IXUSR, "the commit-msg hook is not executable"


def test_it_rejects_the_trailer(tmp_path: Path):
    """The condition the guard exists to catch -- it MUST fail here."""
    message = (
        "feat: something\n\nBody.\n\n"
        "Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>\n"
    )
    assert _run_hook(tmp_path, message) != 0


def test_it_rejects_a_lowercase_claude_trailer(tmp_path: Path):
    message = "fix: x\n\nCo-authored-by: claude-agent[bot] <x@y>\n"
    assert _run_hook(tmp_path, message) != 0


def test_it_allows_a_clean_message(tmp_path: Path):
    assert _run_hook(tmp_path, "feat: something\n\nBody, no trailers.\n") == 0


def test_it_allows_the_autogenerated_footer(tmp_path: Path):
    """The P5.5-prescribed citation form must pass."""
    message = (
        "feat: something\n\nBody.\n\n"
        "[autogenerated by Claude Opus 4.8 v2.1.231 on 2026-08-28 20:00:00 EDT]\n"
    )
    assert _run_hook(tmp_path, message) == 0


def test_it_does_not_fire_on_prose_mentioning_the_phrase(tmp_path: Path):
    """A commit that DESCRIBES stripping the trailer is not itself a violation --
    the hook matches only a trailer LINE, not the words in the body."""
    message = (
        "chore: squash-land to strip Co-Authored-By trailers per P5.5\n\n"
        "The source commits carried Co-Authored-By: Claude; this squash removes them.\n"
    )
    assert _run_hook(tmp_path, message) == 0
